// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AllocerServiceClient is the client API for AllocerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AllocerServiceClient interface {
	Alloc(ctx context.Context, in *AllocRequest, opts ...grpc.CallOption) (*AllocResponse, error)
}

type allocerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAllocerServiceClient(cc grpc.ClientConnInterface) AllocerServiceClient {
	return &allocerServiceClient{cc}
}

func (c *allocerServiceClient) Alloc(ctx context.Context, in *AllocRequest, opts ...grpc.CallOption) (*AllocResponse, error) {
	out := new(AllocResponse)
	err := c.cc.Invoke(ctx, "/pb.AllocerService/Alloc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AllocerServiceServer is the server API for AllocerService service.
// All implementations must embed UnimplementedAllocerServiceServer
// for forward compatibility
type AllocerServiceServer interface {
	Alloc(context.Context, *AllocRequest) (*AllocResponse, error)
	mustEmbedUnimplementedAllocerServiceServer()
}

// UnimplementedAllocerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAllocerServiceServer struct {
}

func (UnimplementedAllocerServiceServer) Alloc(context.Context, *AllocRequest) (*AllocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alloc not implemented")
}
func (UnimplementedAllocerServiceServer) mustEmbedUnimplementedAllocerServiceServer() {}

// UnsafeAllocerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AllocerServiceServer will
// result in compilation errors.
type UnsafeAllocerServiceServer interface {
	mustEmbedUnimplementedAllocerServiceServer()
}

func RegisterAllocerServiceServer(s grpc.ServiceRegistrar, srv AllocerServiceServer) {
	s.RegisterService(&AllocerService_ServiceDesc, srv)
}

func _AllocerService_Alloc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllocerServiceServer).Alloc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AllocerService/Alloc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllocerServiceServer).Alloc(ctx, req.(*AllocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AllocerService_ServiceDesc is the grpc.ServiceDesc for AllocerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AllocerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AllocerService",
	HandlerType: (*AllocerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Alloc",
			Handler:    _AllocerService_Alloc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
